# Generated by Django 5.0.6 on 2024-06-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='task',
        ),
        migrations.AddField(
            model_name='user',
            name='task',
            field=models.ManyToManyField(related_name='users', to='task.task'),
        ),
    ]
